[package]
name = "debugasync/fixedmath"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "deterministic fixed point math for lockstep and rollback on roblox"
